services:
  - type: web
    name: wedding-gallery
    env: python
    buildCommand: pip install -r requirements.txt && python wedding_gallery/manage.py collectstatic --no-input && python wedding_gallery/manage.py migrate
    startCommand: cd wedding_gallery && gunicorn wedding_gallery.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
